// <auto-generated />
using System;
using ConstrutoraViverSA.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConstrutoraViverSA.Infraestrutura.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220923153607_UpdateDatabaseStructure")]
    partial class UpdateDatabaseStructure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConstrutoraViverSA.Domain.Funcionario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cargo")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NumCtps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("ConstrutoraViverSA.Domain.Material", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("Tipo")
                        .HasColumnType("int");

                    b.Property<double?>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Materiais");
                });

            modelBuilder.Entity("ConstrutoraViverSA.Domain.Obra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<long>("OrcamentoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PrazoConclusao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TipoObra")
                        .HasColumnType("int");

                    b.Property<double?>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Obras");
                });

            modelBuilder.Entity("ConstrutoraViverSA.Domain.ObraFuncionarios", b =>
                {
                    b.Property<long>("FuncionarioId")
                        .HasColumnType("bigint");

                    b.Property<long>("ObraId")
                        .HasColumnType("bigint");

                    b.HasKey("FuncionarioId", "ObraId");

                    b.HasIndex("ObraId");

                    b.ToTable("ObraFuncionarios");
                });

            modelBuilder.Entity("ConstrutoraViverSA.Domain.ObraMateriais", b =>
                {
                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint");

                    b.Property<long>("ObraId")
                        .HasColumnType("bigint");

                    b.HasKey("MaterialId", "ObraId");

                    b.HasIndex("ObraId");

                    b.ToTable("ObraMateriais");
                });

            modelBuilder.Entity("ConstrutoraViverSA.Domain.Orcamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoObra")
                        .HasColumnType("int");

                    b.Property<double?>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Orcamentos");
                });

            modelBuilder.Entity("ConstrutoraViverSA.Domain.ObraFuncionarios", b =>
                {
                    b.HasOne("ConstrutoraViverSA.Domain.Funcionario", "Funcionario")
                        .WithMany("ObraFuncionarios")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstrutoraViverSA.Domain.Obra", "Obra")
                        .WithMany("ObraFuncionarios")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("ConstrutoraViverSA.Domain.ObraMateriais", b =>
                {
                    b.HasOne("ConstrutoraViverSA.Domain.Material", "Material")
                        .WithMany("ObraMateriais")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstrutoraViverSA.Domain.Obra", "Obra")
                        .WithMany("ObraMateriais")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("ConstrutoraViverSA.Domain.Funcionario", b =>
                {
                    b.Navigation("ObraFuncionarios");
                });

            modelBuilder.Entity("ConstrutoraViverSA.Domain.Material", b =>
                {
                    b.Navigation("ObraMateriais");
                });

            modelBuilder.Entity("ConstrutoraViverSA.Domain.Obra", b =>
                {
                    b.Navigation("ObraFuncionarios");

                    b.Navigation("ObraMateriais");
                });
#pragma warning restore 612, 618
        }
    }
}
