namespace ConstrutoraViverSA.Domain.Enums
{
    public enum CargoEnum
    {
		SocioProprietário = 0,
		Recepcionista = 1,
		AuxiliarSuprimentos = 2,
		AssistenteSuprimentos = 3,
		AualistaSuprimentos = 4,
		GerenteSuprimentos = 5,
		AuxiliarRecursosHumanos = 6,
		AssistenteRecursosHumanos = 7,
		AnalistaRecursosHumanos = 8,
		GerenteRecursosHumanos = 9,
		TecnicoSaúdeSegurançaTrabalho = 10,
		AuxiliarFinanceiro = 11,
		AssistenteFinanceiro = 12,
		AnalistaFinanceiro = 13,
		GerenteFinanceiro = 14,
		Almoxarife = 15,
		AnalistaQualidade = 16,
		GerenteQualidade = 17,
		MenorAprendiz = 18,
		Estágiario = 19,
		EngenheiroCivil = 20,
		Arquiteto = 21,
		TecnicoEdificações = 22,
		DiretorFabrica = 23,
		Pedreiro = 24,
		PedreiroAcabamento = 25,
		Carpinteiro = 26,
		MestreObras = 27,
		Servente = 28,
		Armador = 29,
	}
}
